/** Zettelkasten uit Capacities, omgezet naar wiki-artikelen met @-koppelingen. */
export const ZETTEL_ARTICLES: Array<{
  slug: string;
  title: string;
  category: string;
  dienst: string;
  summary: string;
  body: string;
  metadata: Record<string, string>;
}> = [
  {
    slug: "methane-bericht-structuur",
    title: "METHANE bericht structuur",
    category: "Inzet",
    dienst: "Ambulance, Brandweer, Meldkamer",
    summary: "Wat is het? METHANE is een gestandaardiseerd rapportageformat voor de eerste eenheid ter plaatse bij een grootschalig incident. Het zorgt voor snelle en complete informatieoverdracht naar de meldkamer en opschaling. De…",
    body: "Wat is het?\n\nMETHANE is een gestandaardiseerd rapportageformat voor de eerste eenheid ter plaatse bij een grootschalig incident. Het zorgt voor snelle en complete informatieoverdracht naar de meldkamer en opschaling.\n\nDe letters\n\nM — Major incident\n\n- Ja of nee. Bevestig of er sprake is van een grootschalig incident.\n\nE — Exact location.\n\n- Geef de exacte locatie door inclusief rijrichting, hectometerpaal of adres.\n\nT — Type of incident.\n\n- Wat is er gebeurd? Brand, aanrijding, explosie, chemisch incident.\n\nH — Hazards.\n\n- Welke gevaren zijn aanwezig of te verwachten? Gevaarlijke stoffen, instortingsgevaar, verkeer.\n\nA — Access.\n\n- Hoe kom je er? Beste aanrijroute voor hulpdiensten.\n\nN — Number of casualties.\n\n- Hoeveel slachtoffers, welke categorie (T1/T2/T3/T0).\n\nE — Emergency services.\n\n- Welke diensten zijn al ter plaatse en wat is er nog nodig?\n\nGebruik in de praktijk\n\nDit format gebruik je zodra je als eerste ter plaatse bent bij een incident met meerdere slachtoffers of gevaren. Geef het bericht zo vroeg mogelijk — ook als je nog niet alles weet. Een onvolledig METHANE is beter dan geen METHANE.\n\nIn relatie tot de @[GGB (Grootschalige Geneeskundige Bijstand)] geeft de verpleegkundige met de @[TV Command & Control] rol een METHANE door.",
    metadata: {
      licentie: "CC-BY-SA-4.0",
      trefwoorden: "GGB, meldkamer",
      ai: "mens",
      bronnen: "Meijer, M. (2026). Zettelkasten. Capacities.",
    },
  },
  {
    slug: "zelfredzaamheid",
    title: "Zelfredzaamheid",
    category: "Methode",
    dienst: "",
    summary: "Zelfredzaamheid is in mijn ogen het vermogen om je eigen broek op te houden op momenten dat het niet gaat zoals normaal of als het echt even tegenzit. Van zelf nadenken over wat je moet doen in plaats van meteen hulp in…",
    body: "Zelfredzaamheid is in mijn ogen het vermogen om je eigen broek op te houden op momenten dat het niet gaat zoals normaal of als het echt even tegenzit. \n\nVan zelf nadenken over wat je moet doen in plaats van meteen hulp in te roepen tot het praktisch oplossen van kleine problemen of uitdagingen in je eigen omgeving.\n\nDenk bijvoorbeeld aan het kunnen afsluiten van de water of gas hoofdkraan, zodat je een lekkage zelf kan oplossen en je eigen psyche en lichaam leren kennen om beter om te gaan met stress en tegenslag.\n\nHet is iets wat in mijn ogen een bredere betekenis heeft, het zegt iets dat je nadenkt over wat je doet, wie je bent, waar je woont en welke uitdagingen of problemen zich voor kunnen doen en je daar van tevoren over nadenkt.\n\nEn als het echt onvoorzien is, dat je de veerkracht en creativiteit hebt om het toch zo goed mogelijk op te lossen. Dit onderwerp gaat in mijn ogen naadloos over in",
    metadata: {
      licentie: "CC-BY-SA-4.0",
      trefwoorden: "",
      ai: "mens",
      bronnen: "Meijer, M. (2026). Zettelkasten. Capacities.",
    },
  },
  {
    slug: "snelweg-locatietips-hectometer-palen",
    title: "Snelweg locatietips / Hectometer palen",
    category: "Procedure",
    dienst: "Ambulance, Meldkamer, Brandweer",
    summary: "Hectometerpalen staan langs rijks- en provinciale wegen en zijn de snelste manier om een exacte locatie door te geven. Er zijn hierbij wat makkelijke ezelsbruggetjes en tips. - AB — Rechterzijde van de weg - CD —…",
    body: "Hectometerpalen staan langs rijks- en provinciale wegen en zijn de snelste manier om een exacte locatie door te geven. Er zijn hierbij wat makkelijke ezelsbruggetjes en tips.\n\n- AB — Rechterzijde van de weg\n\n- CD — Linkerzijde van de weg\n\n- Rechts — Nummering loopt op\n\n- Links — Nummering loopt af\n\n- Li / Re — Geeft rijrichting aan\n\n- Letters — Geven een klaverblad of op/afrit aan\n\nPraktisch\n\nGeef altijd het hectometerpaal-nummer door bij een melding op de snelweg. Combineer dit met rijrichting en zijde zodat elke collega precies weet waar hij moet zijn.",
    metadata: {
      licentie: "CC-BY-SA-4.0",
      trefwoorden: "plaatsbepaling, hectometer",
      ai: "mens",
      bronnen: "Meijer, M. (2026). Zettelkasten. Capacities.",
    },
  },
  {
    slug: "feynman-principe",
    title: "Feynman Principe",
    category: "Methode",
    dienst: "",
    summary: "Een onderwerp in je eigen woorden kunnen uitleggen aan iemand die geen context heeft en 8 jaar oud is. Je hebt dit onderwerp vanuit verschillende perspectieven bekeken en grondig onderzocht. Iemand zou je ook enkele…",
    body: "Een onderwerp in je eigen woorden kunnen uitleggen aan iemand die geen context heeft en 8 jaar oud is. Je hebt dit onderwerp vanuit verschillende perspectieven bekeken en grondig onderzocht.  Iemand zou je ook enkele vragen moeten kunnen stellen. Feitelijk is mijn gehele zettelkast gebouwd volgens dit principe.",
    metadata: {
      licentie: "CC-BY-SA-4.0",
      trefwoorden: "",
      ai: "mens",
      bronnen: "Meijer, M. (2026). Zettelkasten. Capacities.",
    },
  },
  {
    slug: "usar-urban-search-rescue",
    title: "USAR - Urban Search & Rescue",
    category: "Inzet",
    dienst: "Ambulance, Politie, Defensie, Brandweer",
    summary: "- Floris Leenman en Thomas Eckhardt presentatie tijdens Ambulance Masterclass Ongewone Ambulancezorg - Oprichting 2003/2004, ontstaan uit samenwerking met meerdere VR’s. Politie en Defensie dragen ook bij aan USAR. -…",
    body: "- Floris Leenman en Thomas Eckhardt presentatie tijdens Ambulance Masterclass Ongewone Ambulancezorg\n\n- Oprichting 2003/2004, ontstaan uit samenwerking met meerdere VR’s. Politie en Defensie dragen ook bij aan USAR.\n\n- Binnen 6 uur vertrekklaar\n\n- Iedere medewerker van USAR moet in dienst zijn bij een participerende organisatie.\n\n- Hoofdtaak: redden van ingesloten en bedolven slachtoffers.\n\n- Medische team is met name voor eigen mensen en reddingshonden van het team, maar óók voor slachtoffers.\n\n- Worden in heel Nederland ingezet, ondanks dat alle regio’s niet participeren.\n\n- International search and rescue advisory group (INSARAG) is het overkoepelende orgaan, USAR valt onder een “heavy team”.\n\n- Inzet USAR wordt op politiek niveau besproken, die geeft een go/no-go. Een inzet kost ongeveer 1,5 miljoen euro.\n\n- Team kan helemaal zelfvoorzienend 10 dagen lang ingezet worden, eten en andere middelen zijn vaak niet aanwezig in rampgebieden.\n\n- In principe is het team altijd inzetbaar, onderling spreken mensen af dat er voor iedere functie altijd iemand aanwezig is. Dit gaat ook op basis van eerdere inzetten en eerlijke verdeling.\n\n- Coördinatie aardbeving Turkije is voor SAR volledig opgepakt volgens internationale standaarden / guidelines die zijn bepaald door INSARAG. (https://insarag.org/methodology/insarag-guidelines/)\n\n- In tijden van extreme crisis pas extra goed op wat je beloofd en pas triage toe volgens geldende methodiek. Besluiten op zo’n moment kunnen mentaal nog lang doorwerken. Do The Most For The Most\n\n- Medics van USAR werken met LPA en INSARAG onder verantwoordelijkheid MMA.\n\n- Medical & Technical guidance notes: https://insarag.org/methodology/insarag-technical-guidance-notes/\n\n- Iedere zoekhond is getraind voor hele specifieke doeleinden en kan meestal ook alleen die ene taak uitvoeren.\n\n- Team leeft tijdens inzet op pakjes en kant-klaar voedsel\n\n- Vervolgzorg na een reddingsactie kan problematisch zijn, wat doe je na een redding met je slachtoffer?\n\n- USAR wordt ook wel ingezet bij orkanen, daarvoor komt een special hurricane-relieve team.\n\n- Hebben ook een TAST (Technical Assistant Support Team) team dat zorgt voor de coördinatie wat op verzoek kan worden ingezet voor hulp met aansturing en coördinatie\n\n- Moeilijk om te stoppen met een bevrijding als je eenmaal bent begonnen en contact hebt met iemand die vastzit.\n\n- Houdt je bij je eigen methodieken en werkwijzen en werk samen op een creatieve manier met andere diensten.\n\n- Communicatiemiddelen: satteliet-telefoon, portofoons met directe verbinding en Starlink\n\n- Team heeft ook veel contant geld mee voor het regelen, ritselen en ruilen bij lokale bevolking.\n\n- Eerste team was in Turkije na 36 uur op pad, dat team doet een eerste assessment met wat ze gaan doen en waar te beginnen. Toen met alle teams tegelijk gaan werken (alpha, bravo, Charlie en delta). Ook onrust onder de bevolking ’s nachts waardoor het team in het donker tijdelijk is gestopt.\n\n- In Turkije vooral veel jonge mensen die gered worden.\n\n- Na 24 uur komen er ook andere problemen zoals medicatie voor diabetes, bloedverdunners, epilepsie, etc.\n\n- Cultureel zijn er ook veel beperkingen op het gebied van pijnstilling, euthansatie en amputatie. Afhankelijk van het land waar gewewerkt wordt.\n\nVragen\n- Vrijwillig of betaald? Gaat via detachering van eigen werkgevers, uren voor uitzending en oefenen worden regulier betaald. Geen extra uren of vergoedingen.\n- Beveiliging en veiligheid? Lokale bevolking vraagt om hulp en bevestiging voor familie. Honden kunnen de aanwezigheid van levende slachtoffers bepalen door uitgeademde lucht, deze honden slaan alleen aan als mensen echt nog leven en er wordt altijd een dubbele check gedaan.\n- Zoekhulpmiddelen naast honden? Microfoons, camera’s, WBC, etc",
    metadata: {
      licentie: "CC-BY-SA-4.0",
      trefwoorden: "GGB",
      ai: "mens",
      bronnen: "Meijer, M. (2026). Zettelkasten. Capacities.\nINSARAG. (z.d.). Guidelines. https://insarag.org/methodology/insarag-guidelines/",
    },
  },
  {
    slug: "gewonden-verzamelplaats",
    title: "Gewonden Verzamelplaats",
    category: "Inzet",
    dienst: "Ambulance",
    summary: "Deze locatie is bedoeld voor om bij een grootschalige inzet slachtoffers te clusteren en effectief te behandelen zolang er niet voldoende ambulance capaciteit beschikbaar is. - Probeer slachtoffers zoveel mogelijk te…",
    body: "Deze locatie is bedoeld voor  om bij een grootschalige inzet slachtoffers te clusteren en effectief te behandelen zolang er niet voldoende ambulance capaciteit beschikbaar is.\n\n- Probeer slachtoffers zoveel mogelijk te clusteren\n\n- Vraag benodigde hulp zoals MMT\n\n- Verwijs lopende (T3) slachtoffers meteen naar de  bij @[TV Secundaire Triage]\n\n- Zorg voor een locatie die zo dicht mogelijk bij het incident, de @[T3 Verzorglocatie] en goede aan en afvoer route ligt.\n\n- Het liefst een overdekte en verwarmde locatie",
    metadata: {
      licentie: "CC-BY-SA-4.0",
      trefwoorden: "GGB",
      ai: "mens",
      bronnen: "Meijer, M. (2026). Zettelkasten. Capacities.",
    },
  },
  {
    slug: "nht-rode-kruis",
    title: "NHT (Rode Kruis)",
    category: "Inzet",
    dienst: "Ambulance",
    summary: "Wat doet het Rode Kruis? - Alle handelingen aan de buitenkant van de patiënt (EHBO) - Helpen met een indeling van de T3 verzorglocatie - Station 1: Binnenkomst - Primair prioriteren - In overleg met TV AVP slapwrap RTS…",
    body: "Wat doet het Rode Kruis?\n\n- Alle handelingen aan de buitenkant van de patiënt (EHBO)\n\n- Helpen met een indeling van de T3 verzorglocatie\n\n    - Station 1: Binnenkomst\n\n        - Primair prioriteren\n\n        - In overleg met TV AVP slapwrap RTS\n\n    - Station 2: Secundaire triage\n\n        - Overdracht professioneele hulpverlening\n\n    - Station 3: T3 Verzorging\n\n        - Luisterend oor en EHBO\n\n    - Station 4: Check-out\n\n        - Zorg voor snelle doorstroom\n\n- Mentale ondersteuning\n\n- Maken het liefst gebruik van een overdekte en verwarmde @[T3 Verzorglocatie]\n\n- Geoefendheid\n\n    - Minimaal 50 uur per jaar op grote evenementen\n\n    - Deelnemers moeten actieve evenementen hulpverleners zijn\n\n    - Ieder lid doet per jaar minimaal één grote realistische oefening\n\n- Per team kunnen drie triage stations ingericht worden\n\n- Binnen 60 minuten operationeel op plaats incident\n\n- NHT lid doet een snelle eerste triage of eye-balling bij een wachtrij, moeten er mensen eerst gezien worden?\n\n- Teamleden doen SBAR overdracht\n\n- Team is met 8 mensen\n\n    - 6 man maken 3 stations voor de triage (ABCDE, registratie, etc)\n\n- NHT doet geen conclusies maar trekt enkel aan de bel bij het ALS team\n\n- NHT past niet de triage klasse aan, maar zal dan in overleg gaan met AVP ALS @[TV Secundaire Triage]",
    metadata: {
      licentie: "CC-BY-SA-4.0",
      trefwoorden: "GGB",
      ai: "mens",
      bronnen: "Meijer, M. (2026). Zettelkasten. Capacities.",
    },
  },
  {
    slug: "navo-spellingsalfabet",
    title: "NAVO Spellingsalfabet",
    category: "Inzet",
    dienst: "Ambulance, Brandweer, Politie, Meldkamer",
    summary: "Het NAVO-spellingsalfabet is de internationale standaard om letters eenduidig door te geven, ook bij ruis of dialect. Iedereen in uniform heeft er baat bij. Letters - A Alfa - B Bravo - C Charlie - D Delta - E Echo - F…",
    body: "Het NAVO-spellingsalfabet is de internationale standaard om letters eenduidig door te geven, ook bij ruis of dialect. Iedereen in uniform heeft er baat bij.\n\nLetters\n\n- A Alfa\n- B Bravo\n- C Charlie\n- D Delta\n- E Echo\n- F Foxtrot\n- G Golf\n- H Hotel\n- I India\n- J Juliett\n- K Kilo\n- L Lima\n- M Mike\n- N November\n- O Oscar\n- P Papa\n- Q Quebec\n- R Romeo\n- S Sierra\n- T Tango\n- U Uniform\n- V Victor\n- W Whiskey\n- X Xray\n- Y Yankee\n- Z Zulu\n\nCijfers spreek je per stuk Engels uit. 112 wordt one-one-two.\n\nZie @[Universele locatie aanduidingen] en @[METHANE bericht structuur].",
    metadata: {
      licentie: "CC-BY-SA-4.0",
      trefwoorden: "verbinding, plaatsbepaling",
      ai: "mens",
      bronnen: "Meijer, M. (2026). Zettelkasten. Capacities.",
    },
  },
  {
    slug: "do-the-most-for-the-most",
    title: "Do the most for the most",
    category: "Inzet",
    dienst: "Ambulance",
    summary: "Een spreuk die wordt gebruikt bij onder andere de GGB (Grootschalige Geneeskundige Bijstand) (grootschalige geneeskundige bijstand) en andere grootschalige incidenten. Het gaat erom dat je de juiste prioriteiten stelt,…",
    body: "Een spreuk die wordt gebruikt bij onder andere de @[GGB (Grootschalige Geneeskundige Bijstand)] (grootschalige geneeskundige bijstand) en andere grootschalige incidenten. Het gaat erom dat je de juiste prioriteiten stelt, je niet vast laat zetten en zoveel mogelijk doet voor zoveel mogelijk mensen.\n\nJe gaat dus niet één persoon uitgebreid behandelen maar liever 10 kort en de meest noodzakelijke handelingen. Om deze reden is de GGB structuur opgezet bij de @[Ambulance]zodat er wat hulp is bij het stellen van de juiste prioriteiten. Dit kan anders enorm lastig zijn.\n\nHet is belangrijk om dan ook bij je taak te blijven. Het triage team zorgt voor een snelle triage en gaat geen slachtoffers behandelen.\n\nUiteraard kan je dit principe in verschillende contexten toepassen, het principe is bedoeld om zoveel mogelijk mensen in een zo korte mogelijke tijd te helpen, dat kan dus bij iedere hulpdienst toegepast worden.\n\nEnkel methode die helpen bij dit uitgangspunt zijn: @[MARCH Protocol] @[START (Simple Triage and Rapid Treatment)]",
    metadata: {
      licentie: "CC-BY-SA-4.0",
      trefwoorden: "GGB",
      ai: "mens",
      bronnen: "Meijer, M. (2026). Zettelkasten. Capacities.",
    },
  },
  {
    slug: "tv-primaire-triage",
    title: "TV Primaire Triage",
    category: "Inzet",
    dienst: "Ambulance, Brandweer, Politie",
    summary: "De TV Primaire Triage zorgt voor een schifting en prioritering van slachtoffers bij grootschalige incidenten. De Primaire Triage rol wordt in principe opgenomen door de tweede ambulance en dit team zorgt ervoor dat dat…",
    body: "De  TV Primaire Triage zorgt voor een schifting en prioritering van slachtoffers bij grootschalige incidenten. De Primaire Triage rol wordt in principe opgenomen door de tweede ambulance en dit team zorgt ervoor dat dat slachtoffers zo snel mogelijk en zo goed mogelijk in kaart worden gebracht middels slab wraps, zodat deze mensen de juiste hulp krijgen en ook zo snel mogelijk worden afgevoerd.\n\nZorg ervoor dat er enkel levensreddende handelingen worden uitgevoerd bij gewonde slachtoffers en leg de prioriteit op het zo snel mogelijk in kaart brengen van alle slachtoffers zodat iedereen zo snel mogelijk de juiste hulp krijgt. Do The Most For The Most\n\nBeide (ACH + AVP)\n\n- Blijf als team bij elkaar\n\n- Bepaal inzet vakken en indien nodig zonering in overleg met politie bij extreem geweld of brandweer bij brand, ongevallen en gevaarlijke stoffen incidenten.\n\n- Spreek een tijdstip af voor afstemming met @[TV Command & Control] en deel overzichtstekening. Spreek een locatie af voor @[Gewonden Verzamelplaats] en eventueel een @[T3 Verzorglocatie].\n\n- Rode hesjes aantrekken\n\n- Regel bij onvoldoende ambulance capaciteit een @[Gewonden Verzamelplaats] in overleg met COMMAND\n\nACH\n\n- Maakt een overzichtstekening\n\n- Vraagt ambulances aan voor transport T1 en T2 bij @[TV Command & Control]\n\n- Houdt een totaaloverzicht bij van T1, T2 , T3 en overleden slachtoffers.\n\n- Laat @[TV Treatment] een bestemming regelen voor ambulances die meteen gaan vervoeren, dit is uniek in NN. Je kan ze per porto aanvragen via een andere TV of langs treatment sturen voor mondeling overleg. Dit laatste heeft de voorkeur in het kader van @[Ether Discipline]\n\nAVP\n\n- Voert de triage uit en deelt slab wraps uit\n\n- Maak hiervoor gebruik van hulpmiddelen zoals het stroomschema “primaire triage op vindplaats”.\n\n- T3 meteen doorsturen naar @[T3 Verzorglocatie]\n\n- Heeft portofonisch contact met triërende eenheden indien coördinatie nodig is van meerdere teams\n\nCommunicatie\n\n- TV AVP: Schakelt naar opgegeven bijstandskanaal voor contact uitvoerende eenheden\n\n- TV ACH: Schakelt naar opgegeven bijstandskanaal voor contact met alle TV’s en OVD’s.\n\n- Bij inzet van meerdere triërende teams is wordt TRIAGE het coördinerende team. Geeft teams roepnamen: TRIAGE A, TRIAGE B of in tactische setting: TACTISCH A, TACTISCH B.\n\n- Gebruik het @[NAVO Spellingsalfabet]\n\nPRIMAIRE TRIAGE : OP VINDPLAATS (66739980-e064-462f-9a75-a6eb1e80e318.jpg)\n\nPRIMAIRE TRIAGE : OP VINDPLAATS",
    metadata: {
      licentie: "CC-BY-SA-4.0",
      trefwoorden: "GGB, triage",
      ai: "mens",
      bronnen: "Meijer, M. (2026). Zettelkasten. Capacities.",
    },
  },
  {
    slug: "pariter-systeem-ambulancezorg",
    title: "Pariter Systeem Ambulancezorg",
    category: "Inzet",
    dienst: "Ambulance, Meldkamer",
    summary: "Het Pariter-systeem is een landelijk ICT-systeem en netwerk van Ambulancezorg Nederland (AZN) dat specifiek is ontworpen voor ritlogging en het coördineren van ambulancebijstand. Het systeem stelt meldkamers in staat om…",
    body: "Het Pariter-systeem is een landelijk ICT-systeem en netwerk van Ambulancezorg Nederland (AZN) dat specifiek is ontworpen voor ritlogging en het coördineren van ambulancebijstand. Het systeem stelt meldkamers in staat om tijdens grootschalige incidenten, crises of acute onderbezetting naadloos extra ambulances en bijstand uit andere regio's aan te vragen en te volgen.\n\nHet systeem draait op een landelijke server en heeft als doel het makkelijker verlenen van bijstand, patiënten spreiding en opschaling bij regionale tekorten",
    metadata: {
      licentie: "CC-BY-SA-4.0",
      trefwoorden: "GGB",
      ai: "mens",
      bronnen: "Meijer, M. (2026). Zettelkasten. Capacities.",
    },
  },
  {
    slug: "medische-locatie-aanduidingen",
    title: "Medische Locatie Aanduidingen",
    category: "Procedure",
    dienst: "Ambulance",
    summary: "Medische plaatsbepalingen beschrijven waar iets zit, waar je iets doet en welke kant je op kijkt. Dit overzicht loopt van algemeen naar specifiek: eerst de richtingen op het hele lichaam, dan de lijnen en vlakken waar…",
    body: "Medische plaatsbepalingen beschrijven waar iets zit, waar je iets doet en welke kant je op kijkt. Dit overzicht loopt van algemeen naar specifiek: eerst de richtingen op het hele lichaam, dan de lijnen en vlakken waar je naar verwijst, daarna het hart en het ECG, en tot slot de voor- en achtervoegsels waarmee je elke term zelf uit elkaar kunt halen.\n\nRichting is bijna altijd relatief. De knie ligt distaal van de heup en proximaal van de enkel. Links en rechts zijn altijd vanuit de patiënt gezien, nooit vanuit jou.\n\nHoe je een term uit elkaar haalt\n\nDe meeste medische termen zijn opgebouwd uit een voorvoegsel, een orgaan of weefsel, en een achtervoegsel. Ken je de drie stukken, dan kun je een woord lezen dat je nog nooit hebt gezien.\n\n> Peri-card-itis = eromheen + hart + ontsteking = ontsteking van het hartzakje.\n\n> Tachy-cardie = snel + hart = een te snelle hartslag.\n\n> Hepato-megalie = lever + vergroting = een vergrote lever.\n\nRichtingen op het lichaam\n\n> Bij een CVA zit de uitval contralateraal: een bloeding of infarct links in de hersenen geeft uitval rechts.\n\nHanden, voeten en ledematen\n\nAan hand en voet krijgt dorsaal een eigen betekenis. Daar is het niet de rugzijde van het lichaam, maar de bovenkant van hand of voet.\n\nReferentielijnen en vlakken\n\nDeze lijnen gebruik je om een plek precies te beschrijven, bijvoorbeeld voor een ECG-elektrode of een auscultatiepunt.\n\nDe buik in kwadranten\n\nTrek een denkbeeldig kruis door de navel en je hebt vier kwadranten. Dat is de snelste manier om buikpijn te beschrijven.\n\nDaarnaast gebruik je drie plekken in de middenlijn: epigastrisch is boven de navel onder het borstbeen, umbilicaal is rondom de navel, en suprapubisch is boven het schaambeen, waar de blaas ligt.\n\nHet hart: punten en wanden\n\nHet hart staat schuin en met de punt naar linksonder. Daardoor voelt de naamgeving in het begin omgekeerd: de basis zit boven en de apex zit onder.\n\nWelke ECG-afleiding kijkt naar welke wand\n\nElke afleiding kijkt vanuit een eigen hoek naar het hart. Zie je afwijkingen in een groepje afleidingen dat bij elkaar hoort, dan wijst dat naar één wand. Welke kransslagader daarbij hoort verschilt per patiënt, dus de laatste kolom is een richting en geen zekerheid.\n\nDe lagen van de hartwand, van binnen naar buiten\n\n> Loopt de ruimte tussen die twee bladen vol met bloed of vocht, dan kan het hart zich niet meer vullen. Dat is een harttamponnade.\n\nVoorvoegsels: hart, bloed en vaten\n\nVoorvoegsels: longen en luchtwegen\n\nVoorvoegsels: buik en spijsvertering\n\nVoorvoegsels: nieren, blaas en voortplanting\n\nVoorvoegsels: zenuwen, botten en huid\n\nVoorvoegsels: hoeveel of hoe erg\n\nAchtervoegsels: wat er aan de hand is\n\nWat de arts nog moet nakijken\n- De koppeling van ECG-wand naar afleiding is standaard, maar het bijbehorende vat verschilt per patiënt door de dominantie van de kransslagaders. Dekt \"meestal\" dat voldoende af?\n- Posterior infarct: is het spiegelbeeld in V1 tot V3 met bevestiging via V7 tot V9 nog de gangbare formulering?\n- De referentielijnen staan er bewust zonder protocolregel bij. Moeten de landmarks voor bijvoorbeeld thoraxdecompressie erbij, dan komen die uit de actuele LPA en niet uit dit overzicht.\n- Myelo- betekent zowel ruggenmerg als beenmerg. Is die dubbele betekenis zo bruikbaar genoeg?\n- Palmair en volair worden door elkaar gebruikt. Heeft er één de voorkeur in de opleiding?",
    metadata: {
      licentie: "CC-BY-SA-4.0",
      trefwoorden: "plaatsbepaling",
      ai: "mens",
      bronnen: "Meijer, M. (2026). Zettelkasten. Capacities.",
    },
  },
  {
    slug: "ether-discipline",
    title: "Ether Discipline",
    category: "Inzet",
    dienst: "Ambulance",
    summary: "Ether discipline is een principe wat toegepast wordt bij radio communicatie, dit komt weg uit een tijd dat slechts één persoon tegelijk een lijn bezet kan houden in tegenstelling tot moderne telefonie en communicatie.…",
    body: "Ether discipline is een principe wat toegepast wordt bij radio communicatie, dit komt weg uit een tijd dat slechts één persoon tegelijk een lijn bezet kan houden in tegenstelling tot moderne telefonie en communicatie. Zoals C2000, GSM en 3G/4G/5G.\n\nBij geüniformeerde diensten is ether discpline echter nog altijd een begrip wat van toepassing is, echter wordt dit in de dag dagelijkse situatie vaak niet strak toegepast wat erin resulteert dat dit op belangrijke momenten ook niet gedaan wordt. Hierin zouden we een mooie tussenweg kunnen zoeken die werkbaar en duidelijk is.\n\nCommando’s\n\n- Openen gesprek.\n\n    - Eenheid A (jij) voor Eenheid B (de ander)\n\n- *Einde bericht.*\n\n    - Over.\n\n- Gesprek sluiten, verdere reactie niet nodig\n\n    - Sluit.\n\n- Wacht even op nader bericht.\n\n    - Stand-By.\n\nBelangrijke regels\n\n- Luisteren voordat je spreekt.\n\n- Wacht totdat het gesprek van iemand anders gesloten is, tenzij spoed.\n\n- Communiceer alleen noodzakelijk info en probeer berichten duidelijk over te brengen.\n\n- Maak gebruik van het @[NAVO Spellingsalfabet]\n\n- Maak gebruik van @[Universele locatie aanduidingen]",
    metadata: {
      licentie: "CC-BY-SA-4.0",
      trefwoorden: "GGB, verbinding",
      ai: "mens",
      bronnen: "Meijer, M. (2026). Zettelkasten. Capacities.",
    },
  },
  {
    slug: "universele-locatie-aanduidingen",
    title: "Universele locatie aanduidingen",
    category: "Procedure",
    dienst: "Ambulance, Brandweer",
    summary: "Iets wat altijd terugkomt uit evaluaties, is dat de communicatie beter kan. Een van die dingen die beter kan, is de aanduiding van een locatie. Waar je bent, waar je naartoe wilt, of waar we het over hebben. In de…",
    body: "Iets wat altijd terugkomt uit evaluaties, is dat de communicatie beter kan. Een van die dingen die beter kan, is de aanduiding van een locatie. Waar je bent, waar je naartoe wilt, of waar we het over hebben. In de hulpverlening is dit een ontzettend belangrijk onderwerp en hier is nogal eens discussie over.\n\nEtages / Verdiepingen\n\nWe spreken over verdiepingen. Waarbij de begane grond de verdieping is gelijk staat met het maaiveld, betreft het een complex pand met meerder (tussen) verdiepingen dan houden we de zijde met de voordeur aan of de door de eerste aanhield aangegeven alpha zijde als het niet duidelijk is. \n\n- Begane grond\n\n    - Voer gelijk aan het maaiveld. (Straatniveau)\n\n- Kelder(s)\n\n    - Kelder -1, etc.\n\n- Alles boven begane grond\n\n    - Eerste etage, etage twee, etc.\n\n- Tussenverdieping- Verdieping 1,5, etc. Alleen indien het anders niet aangeduid staat.\n\nZijdes\n\nMet de klok mee gerekend (linksom)\n\n- Alpha - Voorzijde (Gevel met de voordeur of zoals aangegeven door de eerste ter plaatse indien dit niet duidelijk is) Bijvoorbeeld: Alpha zijde aan de kant van de Rijksweg.\n\n- Bravo - Linkerzijde\n\n- Charlie - Achterzijde\n\n- Delta - Rechterzijde\n\nNATO/NAVO Alfabet\n\nDeze moet iedere geüniformeerde kennen in het kader van @[Ether Discipline] en zorgt ervoor dat er geen spraakverwarring kan ontstaan. Ook bij slechte verbindingen. Gebruik het @[NAVO Spellingsalfabet].",
    metadata: {
      licentie: "CC-BY-SA-4.0",
      trefwoorden: "plaatsbepaling",
      ai: "mens",
      bronnen: "Meijer, M. (2026). Zettelkasten. Capacities.",
    },
  },
  {
    slug: "start-simple-triage-and-rapid-treatment",
    title: "START (Simple Triage and Rapid Treatment)",
    category: "Inzet",
    dienst: "Ambulance",
    summary: "Primaire triage is de eerste snelle sortering van slachtoffers bij een grootschalig incident. Doel: in zo kort mogelijke tijd bepalen wie direct levensreddend handelen nodig heeft. In de wordt deze triage toegepast door…",
    body: "Primaire triage is de eerste snelle sortering van slachtoffers bij een grootschalig incident. Doel: in zo kort mogelijke tijd bepalen wie direct levensreddend handelen nodig heeft. In de  wordt deze triage toegepast door @[TV Primaire Triage]\n\nTriagecategorieën\n\nT1 — Onmiddellijk Levensbedreigende aandoening die direct behandeling vereist. Rood label.\n\nT2 — Urgent Ernstig maar stabiel. Kan korte tijd wachten. Geel label.\n\nT3 — Niet urgent Lichte verwondingen, kan zelfstandig lopen. Groen label.\n\nT0 — Overleden Geen tekenen van leven. Zwart label.\n\nSTART-methode\n\nSimple Triage And Rapid Treatment. Tijd per slachtoffer: maximaal 30 seconden.\n\n1. Loopt het slachtoffer? → T3\n\n2. Ademhaling aanwezig na vrijmaken luchtweg? → Nee = Overleden.\n\n3. Ademfrequentie > 30/min? → T1\n\n4. Capillaire refill > 2 sec of geen radialispols? → T1\n\n5. Bewustzijn: voert opdrachten uit? → Nee = T1, Ja = T2",
    metadata: {
      licentie: "CC-BY-SA-4.0",
      trefwoorden: "GGB, triage, TECC",
      ai: "mens",
      bronnen: "Meijer, M. (2026). Zettelkasten. Capacities.",
    },
  },
  {
    slug: "altis",
    title: "ALTIS",
    category: "Methode",
    dienst: "Ambulance",
    summary: "Methode voor het systematisch afnemen van een anamnese. - Aard van de klachten - Hoe is het ontstaan? Wat is de aanleiding? - Locatie - Waar zit het, hoe groot is het? - Tijd - Wat is het beloop? Is het erger of beter…",
    body: "Methode voor het systematisch afnemen van een anamnese.\n\n- Aard van de klachten\n\n    - Hoe is het ontstaan? Wat is de aanleiding? \n\n- Locatie\n\n    - Waar zit het, hoe groot is het?\n\n- Tijd\n\n    - Wat is het beloop? Is het erger of beter geworden?\n\n- Intesiteit?\n\n    - Is het continu aanwezig? Wat voor  geeft de patiënt?\n\n- Samenhang\n\n    - Zijn er zaken die deze klacht luxeren of verergeren? Wat is de bredere context? Is het al vaker voorgekomen, wat is er toen gebeurd?",
    metadata: {
      licentie: "CC-BY-SA-4.0",
      trefwoorden: "",
      ai: "mens",
      bronnen: "Meijer, M. (2026). Zettelkasten. Capacities.",
    },
  },
  {
    slug: "socrates",
    title: "SOCRATES",
    category: "Methode",
    dienst: "Ambulance",
    summary: "- Site - Waar - Onset - Begin / verloop - Character - Aard - Radiation - Uitraling naar ander gebied - Associations -Benauwd, zweten, koorts, uitval, paliptaties, misselijk/braken. - Time - Beloop constant/aanvallen -…",
    body: "- Site - Waar\n\n- Onset - Begin / verloop\n\n- Character - Aard\n\n- Radiation - Uitraling naar ander gebied\n\n- Associations -Benauwd, zweten, koorts, uitval, paliptaties, misselijk/braken.\n\n- Time - Beloop constant/aanvallen\n\n- Exacerbations - Effect bij inspanning, rust, houding\n\n- Severity - NRS en functionele beperkingen",
    metadata: {
      licentie: "CC-BY-SA-4.0",
      trefwoorden: "",
      ai: "mens",
      bronnen: "Meijer, M. (2026). Zettelkasten. Capacities.",
    },
  },
  {
    slug: "oppervlaktereddingsteam-ovrt",
    title: "Oppervlaktereddingsteam (OVRT)",
    category: "Inzet",
    dienst: "Brandweer",
    summary: "Deze teams redden mensen en dieren uit het water. Daarbij blijven de oppervlakteteams aan de oppervlakte en gaan ze maximaal 200 meter uit de boot of van de kant. In Nederland worden deze teams geleverd door de…",
    body: "Deze teams redden mensen en dieren uit het water. Daarbij blijven de oppervlakteteams aan de oppervlakte en gaan ze maximaal 200 meter uit de boot of van de kant. In Nederland worden deze teams geleverd door de @[Brandweer]\n\nMogelijkheden\n\n- Maximaal 200 meter uit de boot of vanaf de kant\n\n- Altijd aangelijnd\n\n- Kunnen ook optreden op ijs\n\n- Redden allen op het wateroppervlakte en gaan niet onder water\n\nMaterialen\n\n- Reddingsbord (prikslee)\n\n- Duikbril\n\n- Kuipbrancard\n\n- Werplijn 30 meter\n\n- Werklijn 200 meter\n\n- Speciaal OVRT pak",
    metadata: {
      licentie: "CC-BY-SA-4.0",
      trefwoorden: "GGB, redding",
      ai: "mens",
      bronnen: "Meijer, M. (2026). Zettelkasten. Capacities.",
    },
  },
  {
    slug: "tv-command-control",
    title: "TV Command & Control",
    category: "Inzet",
    dienst: "Ambulance, Brandweer, Politie, Meldkamer",
    summary: "Dit is de eerste taak als de GGB structuur wordt opgezet, COMMAND heeft de eerste coördinatie voor de witte kolom ter plaatse en heeft een belangrijke rol voor de opstart van een grootschalig incident. Veiligheid is het…",
    body: "Dit is de eerste taak als de GGB structuur wordt opgezet, COMMAND heeft de eerste coördinatie voor de witte kolom ter plaatse en heeft een belangrijke rol voor de opstart van een grootschalig incident. Veiligheid is het belangrijkste.\n\n- Herkenbaar aan het groene hesje en de groene lamp bij de ambulance.\n\n- Wat is veilig en wat niet? Overleg brandweer.\n\n- Overleg politie bij (extreem) geweld\n\n- Do The Most For The Most\n\n- Treat first what kills first\n\n- Wees pragmatisch\n\n- Pas @[Ether Discipline] toe\n\nBeide (ACH + AVP)\n\n- Bepaal indien nodig inzetvakken en bij IGS of tactische inzetten in overleg met politie en brandweer hot, warm en cold zones.\n\nACH\n\n- Organiseer en coördineer het ambulancecircuit\n\n- Ondersteun de TV Transport waar mogelijk\n\n- Zorg bij incidenten met gevaarlijke stoffen of een Tactische inzet voor veilige en bovenwindse aanrijroutes voor overige eenheden\n\n- Bepaal in overleg met Politie en ✱ Brandweer de locaties van @[T3 Verzorglocatie] , de @[Gewonden Verzamelplaats]\n\n- Maak een overzichtstekening van alle bovenstaande en het incident\n\n- Hoe pak je dit methodisch aan?\n\n- Heeft contact met alle TV’s over benodigde ambulances of andere hulp en stemt dit af met de OVDG en TV Transport.\n\nAVP\n\n- Informeren MKA en OVD-G\n\n- Meld zich in bij de meldkamer als COMMAND\n\n- Voer een verkenning uit van maximaal twee minuten en geeft een METHANE Bericht\n\n- Geeft duidelijke instructies aan de TV’s, legt de inzetvakken uit en geeft veiligheidsinstructies zoals afgestemd met Politie en Brandweer tijdens het motorkap overleg.\n\nCommunicatie\n\n- Mobilofoon blijft in de gespreksgroep en wordt door de meldkamer gekoppeld aan een incidentgroep voor contact met aanrijdende eenheden\n\n- Schakel allebei de portofoon naar de opgegeven bijstandsgroep voor contact met OVD’g en alle andere TV’s\n\n- Team blijft niet bij elkaar.\n\n- Chauffeur blijft in de auto en is zichtbaar aanwezig.",
    metadata: {
      licentie: "CC-BY-SA-4.0",
      trefwoorden: "GGB",
      ai: "mens",
      bronnen: "Meijer, M. (2026). Zettelkasten. Capacities.",
    },
  },
  {
    slug: "habituatie-filters",
    title: "Habituatie filters",
    category: "Methode",
    dienst: "",
    summary: "Habituatiefilter (ook wel gewenningsfilter genoemd) is het ingebouwde 'spamfilter' van je brein. Het is een cognitief mechanisme dat ervoor zorgt dat je hersenen steeds minder reageren op herhaalde, niet-bedreigende…",
    body: "Habituatiefilter (ook wel gewenningsfilter genoemd) is het ingebouwde 'spamfilter' van je brein. Het is een cognitief mechanisme dat ervoor zorgt dat je hersenen steeds minder reageren op herhaalde, niet-bedreigende prikkels. Hierdoor kun je irrelevante informatie buitensluiten en je focussen op wat echt belangrijk.\n\nIn marketing is het nodig om hier het liefst in de eerst 5 seconden van een contact moment doorheen te breken. Je moet meteen emotie opwekken, dat kan positief of negatief zijn, maar het is wel nodig en het moet echt opvallen voor je doelgroep. Niet qua kleuren etc, maar qua boodschap en wat dit triggert. \n\nBron: @[Diary of a CEO]",
    metadata: {
      licentie: "CC-BY-SA-4.0",
      trefwoorden: "",
      ai: "mens",
      bronnen: "Meijer, M. (2026). Zettelkasten. Capacities.",
    },
  },
  {
    slug: "t3-verzorglocatie",
    title: "T3 Verzorglocatie",
    category: "Inzet",
    dienst: "Ambulance",
    summary: "Een locatie ingericht voor T3 slachtoffers — de groene categorie. Ze kunnen lopen, zijn niet direct in levensgevaar, maar hebben wel aandacht en registratie nodig. Wie richt het in? De TV Secundaire Triage is…",
    body: "Een locatie ingericht voor T3 slachtoffers — de groene categorie. Ze kunnen lopen, zijn niet direct in levensgevaar, maar hebben wel aandacht en registratie nodig.\n\nWie richt het in?\n\nDe @[TV Secundaire Triage] is verantwoordelijk. Het NHT van het Rode Kruis assisteert bij:\n\n- Opbouwen en inrichten van de locatie\n\n- Basis EHBO uitvoeren\n\n- Slachtoffers registreren\n\n- Mentale ondersteuning bieden\n\nPraktisch\n\nKies een locatie buiten het zicht van het incident, toegankelijk voor voertuigen en met voldoende ruimte voor verwachte aantallen.",
    metadata: {
      licentie: "CC-BY-SA-4.0",
      trefwoorden: "GGB, plaatsbepaling",
      ai: "mens",
      bronnen: "Meijer, M. (2026). Zettelkasten. Capacities.",
    },
  },
  {
    slug: "ggb-grootschalige-geneeskundige-bijstand",
    title: "GGB (Grootschalige Geneeskundige Bijstand)",
    category: "Inzet",
    dienst: "Ambulance",
    summary: "De GGB zorgt voor structuur bij grootschalige incidenten binnen de pre-hospitale acute zorg. Het doel is om ernstig gewonde slachtoffers zo snel mogelijk naar ziekenhuizen te vervoeren, en lichtere gewonden passende…",
    body: "De GGB zorgt voor structuur bij grootschalige incidenten binnen de pre-hospitale acute zorg. Het doel is om ernstig gewonde slachtoffers zo snel mogelijk naar ziekenhuizen te vervoeren, en lichtere gewonden passende hulp te bieden.\n\nTaakverantwoodelijken\n\n- @[TV Command & Control]\n\n- @[TV Primaire Triage]\n\n- @[TV Treatment]\n\n- @[TV Secundaire Triage]\n\nAlgemene uitgangspunten\n\n- Verdeel vooraf taken en houdt je daaraan\n\n- Zorg dat je weet met wie je in contact staat\n\n- Pas @[Ether Discipline]\n\n- @[Do the most for the most]\n\n- Ga pragmatisch en praktisch te werk\n\nBegrippen en Definities\n\n- @[T3 Verzorglocatie]\n\n- @[Gewonden Verzamelplaats]\n\n- @[C2000 Verbindingen GGB Noord-Nederland]\n\n- @[NHT (Rode Kruis)]\n\nVaardigheden\n\n- Overzicht maken en houden\n\n- @[METHANE bericht structuur]",
    metadata: {
      licentie: "CC-BY-SA-4.0",
      trefwoorden: "GGB",
      ai: "mens",
      bronnen: "Meijer, M. (2026). Zettelkasten. Capacities.",
    },
  },
  {
    slug: "tv-treatment",
    title: "TV Treatment",
    category: "Inzet",
    dienst: "Ambulance",
    summary: "De taakverantwoordelijke treatment coördineert de behandeling op de Gewonden Verzamelplaats en kan daarbij hulp krijgen van het MMT en het calamiteiten voertuig. Je blijft als team bij elkaar. Belangrijkste taken -…",
    body: "De taakverantwoordelijke treatment coördineert de behandeling op de @[Gewonden Verzamelplaats] en kan daarbij hulp krijgen van het @[MMT] en het calamiteiten voertuig. Je blijft als team bij elkaar.\n\nBelangrijkste taken\n\n- Zorgt voor het inrichten van en coördineren van een @[Gewonden Verzamelplaats]\n\n- Zorg voor behandeling en zo snel mogelijke afvoer van T1 en T2 slachtoffers\n\n- Calamiteiten Voertuig meldt wordt hier ook ingezet met extra middelen en materialen\n\n- Prioriterend MMT arts komt vaak ook ter plaatse om bijvoorbeeld T1 slachtoffers toch in andere ziekenhuizen te krijgen als de level-1 ziekenhuizen vol liggen.\n\nBeide ACH + AVP\n\nAVP\n\n- Zit in een bijstand groep (bijstand 4) met de TV Transport per porto.\n\nACH\n\n- TV Transport zit in de groep met alle TV’s. TV transport zit NIET in hetzelfde kanaal als de",
    metadata: {
      licentie: "CC-BY-SA-4.0",
      trefwoorden: "GGB",
      ai: "mens",
      bronnen: "Meijer, M. (2026). Zettelkasten. Capacities.",
    },
  },
  {
    slug: "6a-regel-gevaarlijke-stoffen",
    title: "6A-regel gevaarlijke stoffen",
    category: "Uitrusting",
    dienst: "Brandweer",
    summary: "De 6A-regel is een geheugensteun voor veilig optreden bij incidenten met gevaarlijke stoffen. Gebruik het totdat het AGS of GAGS aanwezig is en als eerste vuistregel bij incidenten met gevaarlijke stoffen. De 6 A's 1.…",
    body: "De 6A-regel is een geheugensteun voor veilig optreden bij incidenten met gevaarlijke stoffen. Gebruik het totdat het AGS of GAGS aanwezig is en als eerste vuistregel bij incidenten met gevaarlijke stoffen.\n\nDe 6 A's\n\n1. Aanrijden — Altijd bovenwinds aanrijden\n\n2. Afstand houden\n\n    - Onbekende stof: minimaal 100 meter\n\n    - Explosieve stof: minimaal 500 meter\n\n    - Minimum indien stof het toelaat: 25 meter\n\n3. Adembescherming en PBM — Gebruik PBM passend bij de stof, na de opstellijn\n\n4. Apparatuur — Gebruik de juiste meetapparatuur. Pylon plaatsen waar de meter het eerst afgaat\n\n5. Afscherming — Kies de meest veilige plek voor alle activiteiten\n\n6. Aflossing — Voorkom te lange blootstelling en vermoeidheid\n\nBronnen\n\n- YouTube: Brandweer Midden-West Brabant",
    metadata: {
      licentie: "CC-BY-SA-4.0",
      trefwoorden: "PBM, gevaarlijke stoffen",
      ai: "mens",
      bronnen: "Meijer, M. (2026). Zettelkasten. Capacities.\nBrandweer Midden-West Brabant. (z.d.). 6A-regel gevaarlijke stoffen.",
    },
  },
  {
    slug: "never-waste-a-good-crisis",
    title: "Never waste a good crisis",
    category: "Methode",
    dienst: "",
    summary: "Het idee dat je altijd gebruik moet maken van een crisis om veranderingen door te voeren, producten te verkopen of om iets te winnen wat anders niet zou lukken.",
    body: "Het idee dat je altijd gebruik moet maken van een crisis om veranderingen door te voeren, producten te verkopen of om iets te winnen wat anders niet zou lukken.",
    metadata: {
      licentie: "CC-BY-SA-4.0",
      trefwoorden: "",
      ai: "mens",
      bronnen: "Meijer, M. (2026). Zettelkasten. Capacities.",
    },
  },
  {
    slug: "c2000-verbindingen-ggb-noord-nederland",
    title: "C2000 Verbindingen GGB Noord-Nederland",
    category: "Inzet",
    dienst: "Ambulance, Meldkamer",
    summary: "- Pariter systeem (Pariter Systeem Ambulancezorg op de meldkamer, loopt via LSR (Landelijke server ritlogging) systeem, - Bijstand kanalen Command & Control - Bijstandskanalen hebben prioriteiten boven reguliere kanalen…",
    body: "- Pariter systeem (@[Pariter Systeem Ambulancezorg] op de meldkamer, loopt via LSR (Landelijke server ritlogging) systeem,\n\n- Bijstand kanalen Command & Control\n\n- Bijstandskanalen hebben prioriteiten boven reguliere kanalen\n\n- Groningen - 1352 Bijstand 2\n\n- Friesland - 1358 Bijstand 8\n\n- Drenthe - 1364 Bijstand 14\n\n- Reguliere schakeling\n\n- Groepen van de eenheid worden gekoppeld aan de incidentgroep of bijvoorbeeld een bijstandsgroep voor externe bijstand\n\n- Afwijkingen Noord-Nederland tov landelijk\n\n- @[TV Command & Control]blijft in de auto zitten en heeft contact in het bijstand kanaal met OVDG en ook alle TV’s in een bijstandskanaal met de C2000 mobilofoon.\n\n- @[TV Secundaire Triage] AVP staat in een ander bijstand kanaal in contact met de teamleider van het NHT Rode Kruis\n\n- Indien er sprake is van triage met meerdere triërende eenheden komen die in een apart bijstandkanaal, de @[TV Primaire Triage] roept dan ook aan via dat kanaal met uitvoerende eenheden\n\n- Spreeksleutel ingedrukt houden om te zenden als de mast bezet is bij attentegeluidje, dan ben je daarna als eerste aan de beurt.\n\n- Zet apparatuur uit die je niet gebruikt UIT om overbelasting van te voorkomen, dit bijvoorbeeld gebeurd bij het incident Turkish Airlines",
    metadata: {
      licentie: "CC-BY-SA-4.0",
      trefwoorden: "GGB, verbinding",
      ai: "mens",
      bronnen: "Meijer, M. (2026). Zettelkasten. Capacities.",
    },
  },
  {
    slug: "scegs",
    title: "SCEGS",
    category: "Methode",
    dienst: "Ambulance",
    summary: "Een methodiek om systematisch een casus af te gaan zonder iets te vergeten. - Somatisch - Overige klachten en eerder onderzoek - , ALTIS, etc - Cognities - Wat denkt u dat er is? - Waarom hebben mensen gebeld, waar zijn…",
    body: "Een methodiek om systematisch een casus af te gaan zonder iets te vergeten.\n\n- Somatisch - Overige klachten en eerder onderzoek\n\n    - , @[ALTIS], etc\n\n- Cognities - Wat denkt u dat er is?\n\n    - Waarom hebben mensen gebeld, waar zijn ze bang voor? \n\n- Emoties - Benoem emoties en zorgen\n\n    - Benoem wat je doet, waarom, emoties die je ziet, etc.\n\n- Gedrag - Eerder zorgcontact, medicatie, vermijden van activiteiten\n\n    - Wat is er eerder gebeurd? Soms lijkt het misschien minder relevant, maar is dit het wel degelijk. Zijn eerdere zorg contacten gefrustreerd of wat is er anders dan nu? Welke activiteiten doet iemand nu niet, terwijl hij/zij dat normaal wel doet.\n\n- Sociaal - Thuissitautie, mantelzorg (on)veiligheid.\n\n    - Kijk verder dan enkel de hulpvraag, hoe is de situatie thuis en wat is eventueel het vangnet.",
    metadata: {
      licentie: "CC-BY-SA-4.0",
      trefwoorden: "",
      ai: "mens",
      bronnen: "Meijer, M. (2026). Zettelkasten. Capacities.",
    },
  },
  {
    slug: "7-2-methodiek",
    title: "7+2 Methodiek",
    category: "Methode",
    dienst: "Ambulance",
    summary: "1. Ritme 1. P top gevolgd door QRS = sinus 2. HF 3. Geleidingstijden 1. P - QRS - QT - PQ - QTC 2. 1 groot = 200ms 3. 1 klein vakje = 40ms 4. Hartas 5. P-top morfologie 6. QRS Morfologie 7. ST morfologie 1. Vergelijking…",
    body: "1. Ritme\n\n    1. P top gevolgd door QRS = sinus\n\n2. HF\n\n3. Geleidingstijden \n\n    1. P - QRS - QT - PQ - QTC\n\n    2. 1 groot = 200ms\n\n    3. 1 klein vakje = 40ms\n\n4. Hartas\n\n5. P-top morfologie\n\n6. QRS Morfologie\n\n7. ST morfologie\n\n    1. Vergelijking met oud ECG\n\n    2. Conclusie passend bij klinische context",
    metadata: {
      licentie: "CC-BY-SA-4.0",
      trefwoorden: "ECG",
      ai: "mens",
      bronnen: "Meijer, M. (2026). Zettelkasten. Capacities.",
    },
  },
  {
    slug: "march-protocol",
    title: "MARCH Protocol",
    category: "Inzet",
    dienst: "Ambulance",
    summary: "MARCH is de volgorde waarin je letsel aanpakt bij TECC en vergelijkbare inzet: eerst wat iemand het snelst doodt. 1. Massive hemorrhage — levensbedreigend bloedverlies stoppen 2. Airway — vrije ademweg 3. Respiration —…",
    body: "MARCH is de volgorde waarin je letsel aanpakt bij TECC en vergelijkbare inzet: eerst wat iemand het snelst doodt.\n\n1. Massive hemorrhage — levensbedreigend bloedverlies stoppen\n2. Airway — vrije ademweg\n3. Respiration — ademhaling en borstkas\n4. Circulation — shock en resterende bloeding\n5. Hypothermia / Head — onderkoeling voorkomen en hoofdletsel meenemen\n\nJe blijft bij de volgorde. Niet alles tegelijk, wel het belangrijkste eerst. Past bij @[Do the most for the most] en @[START (Simple Triage and Rapid Treatment)]. Bij een groot incident werkt dit naast @[GGB (Grootschalige Geneeskundige Bijstand)].",
    metadata: {
      licentie: "CC-BY-SA-4.0",
      trefwoorden: "GGB, TECC",
      ai: "mens",
      bronnen: "Meijer, M. (2026). Zettelkasten. Capacities.",
    },
  },
  {
    slug: "tv-secundaire-triage",
    title: "TV Secundaire Triage",
    category: "Inzet",
    dienst: "Ambulance",
    summary: "- *TV Secundaire Triage Terug: GGBDatum: 16-10-2025 De taakverantwoordelijke secundaire triage zorgt samen met een NHT Rode Kruis voor een goed georganiseerde T3 Verzorglocatie, de TV Secundair is te herkennen aan het…",
    body: "- *TV Secundaire Triage\n\nTerug: GGBDatum: 16-10-2025\n\nDe taakverantwoordelijke secundaire triage zorgt samen met een NHT Rode Kruis voor een goed georganiseerde @[T3 Verzorglocatie], de TV Secundair is te herkennen aan het blauwe hesje en wordt in een ideale setting uitgevoerd door de 4de ALS ambulance binnen de \n\nBelangrijkste taken TV Secundair**\n\n- Organiseren en coördineren van de Secundaire triage.\n\n- Verifiëren locatie bij @[TV Command & Control] of organiseren.\n\n- Inrichten T3 verzorglocatie\n\n- Wachtruimtes\n\n- Duidelijke routering voor patiënten\n\n- Triage ruimte\n\n- Afmelden\n\n- Registratie NAW voor patiëntregistratiesysteem\n\n- Bemens de triageruimten met ambulanceteams / medici voor Secundaire triage.\n\n- Zorg voor een totaaloverzicht en houdt een log bij (indien mogelijk)\n\n- Zorg voor voldoende capaciteit en maak overcapaciteit beschikbaar\n\n- Vraag voor een T1/T2 slachtoffer direct een ambulance aan bij ACH C&C\n\n- Laat het behandelend team op de T3-Verzorglocatie via de SBAR-methode de overdracht doen aan het gearriveerde ambulanceteam.\n\n- *Laat het ambulanceteam zich na de overdracht (fysiek) melden bij de @[TV Treatment] en vragen om een bestemming.*\n\n- 70 (T1) -20 (T2) -10 (T1) vuistregel aantal slachtoffers\n\n- *Gerelateerd**\n\n- 1401 - Instructeur\n\n- GGB Triage Klassen",
    metadata: {
      licentie: "CC-BY-SA-4.0",
      trefwoorden: "GGB, triage",
      ai: "mens",
      bronnen: "Meijer, M. (2026). Zettelkasten. Capacities.",
    },
  },
];
